sass:
    sass_dir: assets
# Site
repository: neidiom/neidiom.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nedim Hadzimahmutovic
title: Senior DevOps Engineer
email: h.nedim@gmail.com
website: https://github.com/neidiom

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  neidiom
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: neidiom
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Greetings! I'm Nedim, a DevOps engineer with nearly two decades of experience. My expertise lies in Linux server administration and automating cloud systems.

  I am most skilled in the following:
  * <mark>Terraform</mark>,
  * <mark>Ansible</mark>,
  * <mark>AWS Cloud</mark> and,
  * anything <mark>Linux</mark>.

  I love writing scripts in <mark>Ruby</mark> and <mark>Python</mark>.

content:
  - title: Latest Projects
    layout: list
    content:
      - layout: top-middle
        title: 'Loop Platform: Audience, and Community Engagement Platform powered by GoLang Containers, React, and run on AWS Cloud'
        quote: >
          Working on this project was awesome because I had complete creative control.
        description: |
          I helped build this platform from scratch! We used <mark>Golang</mark> for the API, which is great because it creates a single binary that gets deployed as a Docker Container to <mark>AWS AppRunner</mark>.
          Secrets are stored in <mark>AWS Parameter Store</mark> and settings are loaded automatically during deployment to keep things secure.
          I wrote many AWS Lambda scripts for Slack notifications, MySQL backup, Stop/Start services, etc.

          Technologies used are:
          * <mark>Golang</mark> for the API,
          * <mark>React</mark> for the FrontEnd which is deployed to S3 and served by CloudFront.
          * <mark>AWS AppRunner</mark> for deploying Docker Containers,
          * <mark>Terraform</mark> as the Infrastructure as Code solution,
          * <mark>AWS CodePipeline</mark> as the CI/CD,
          * <mark>AWS ParameterStore</mark> as the key-value store
          * <mark>AWS CloudFront</mark> as the CDN solution.

      - layout: top-middle
        title: 'InvestDEFY: Ansible-powered HashiCorp Nomad implementation at a Crypto startup'
        quote: >
          This is one of the greatest setups I worked with.
        description: |
          This company's DevOps is super impressive! Instead of using virtual machines, they built everything on physical servers and managed it with custom Ansible code.
          They have a central list of servers organized into groups, and amazingly, they use just one playbook to manage all of them!
          Only one playbook file is used for dozens of servers so they rely heavily on tags and groups.

          More than 50 custom Ansible roles are being used.

          All services are run from custom Docker images that are built and deployed by the custom Jenkins server. Jenkins is built with the configuration-as-code plugin.
          Makefiles are used in combination with Jenkinsfiles.

          My tasks were to:
          - Refactor the Ansible code,
          - Introduce staging and production hosts inventory and group vars,
          - Create HashiCorp Nomad role and deploy data mining services on Nomad,
          - Create the staging Jenkins server using the configuration-as-code plugin,
          - Dockerize many <mark>Golang</mark> services.

   #
   #
   #
   #       Experience
   #
   #
   #
   #

  - title: Experience
    layout: list
    content:

      - layout: left
        title: Clearview
        sub_title: DevOps Engineer
        caption: 2017 - 2024
        quote: >
          First remote position in a US IT outsourcing company
        description: |
            **I'm keeping project infrastructure running smoothly.** This includes monitoring everything, logging activity, backing things up, and making sure all the needed services are available. I'm always on the lookout for ways to improve it too.
            **I work with all kinds of servers,** from physical ones (bare metal) to cloud-based options like AWS and Google Cloud Platform (GCP).
            **I team up with the developers** to figure out the best technology for each project. I chat with them and the client to make sure we're all on the same page. Once we have a plan, I help them set everything up correctly and troubleshoot any problems.
            **Basically, I'm the infrastructure techie, making sure everything runs behind the scenes for the developers.** I use tools like Terraform for the cloud and Ansible for physical servers.


      - layout: left
        title: BAWAG P.S.K.
        sub_title: DevOps Engineer
        caption: 2018 - 2021
        quote: >
          Helped with the process of moving an Austrian bank to the Cloud
        description: |
            I built services to identify, de-allocate, and shut down idle virtual machines, reducing costs. I was also involved in implementing the Branch Finder web app using a microservice architecture and deploying it on an Azure Kubernetes Service cluster.

      - layout: left
        title: Inservio d.o.o.
        sub_title: Linux System Administrator / DevOps Engineer
        caption: 2009 - 2021
        quote: >
          Started as a small web agency and grew into a managed web hosting provider
        description: |
            A web agency and managed hosting provider. Infrastructure based on dedicated servers hosted with Hetzner and running Proxmox virtual environment. Services isolated with LXC containers running Debian Linux. Containers are deployed with custom Ansible roles.
            Worked with high-traffic web portals to set up services and architecture required to seamlessly handle high-load traffic. Responsible for setting up bare metal servers and containers. Worked with mail servers and web hosting panels. Managed Wordpress instances by WP-CLI and wrote custom scripting in Ruby.

      - layout: left
        title: ICITAP Mission in Bosnia, US DOJ
        sub_title: Linux System Administrator
        caption: 2006 - 2019
        quote: >
          For 14 years, I've gained a ton of experience managing a regional HQ.
        description: |
            Supporting local police agencies and other ICITAP missions by acting as a regional data center and providing email, file sharing, LDAP, and VoIP services with our infrastructure based on Dell PowerEdge 720 and 610 servers running on Xen Server virtualisation software.

      - layout: left
        title: European Union Monitoring Mission in Bosnia
        sub_title: IT Assistant
        caption: 2005 - 2006
        quote: >
          First experience with IT support and working in a regional organization
        description: |
            I used to support the EUMM mission by providing IT assistance both in the region and remotely.

      - layout: left
        title: Linux User Group of Zenica
        sub_title: Linux Sys Admin at local community wireless network
        caption: 2002 - 2005
        quote: >
          First experience with remote Linux servers and wireless networks.
        description: |
            I gained my first Linux skills by being part of this local Linux User Group. The local Faculty of Mechanical Engineering was the first sponsor, providing a dedicated server with a static IP address on which we run a Web and Mail server.
            Later, we grew and ran the first community wireless network, where we experimented with custom IPtables firewalls, an intranet, split DNS systems, and WDS, or Wireless Distribution Systems.


  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in IT, some of my other interests and hobbies are:
      - Traveling
      - Hiking
      - Podcasts

      Location:
      - <mark>Country:</mark> Bosnia & Herzegovina.
      - <mark>Homey town:</mark> Zenica.
      - <mark>Current city:</mark> Sarajevo.
      - <mark>Current location:</mark> Jakarta.

  - title: Certification
    layout: text
    content: |
      - [LPI Linux Essentials](https://github.com/neidiom/neidiom.github.io/blob/main/images/LPI_Nedim_Hadzimahmutovic_Linux_Essentials_LE-1.pdf)

  - title: Scripts
    layout: text
    content: |
      These are some of the public scripts I wrote.
      - [monit2slack](https://github.com/inservio/monit2slack)
      - [Dockerized SSL certificate notification](https://github.com/neidiom/dockerized_ssl_certificate_expiry_notification)
#      - [Zmcli](https://github.com/inservio/zmcli)
#      - [servermonitor](https://github.com/neidiom/servermonitor)

  - title: Publications
    layout: text
    content: |
      A compilation of my AWS-related blog articles compiled into an e-book can be downloaded for free. 
      - [![Read About AWS While Your Coffee Brews](./images/cover_book_Read-About-AWS-While-Your-Coffee-Brews_small.jpg "Read About AWS While Your Coffee Brews")](https://nedtechie.gumroad.com/l/Read_About_AWS_While_Your_Coffee_Brews)
      # - [***Read About AWS While Your Coffee Brews***](https://nedtechie.gumroad.com/l/Read_About_AWS_While_Your_Coffee_Brews)


# Footer
footer_show_references: true
references_title: References provided on this very page :)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
